### ISSUE TITLE
Update "Start a project" documentation with pull #184 changes

### ISSUE THREAD

**Issue by TheoDardel** [blossom-project/blossom-initializr#17]
Default Blossom account password is no longer "system" (see https://github.com/blossom-project/blossom/pull/184)
Patch with a proposal is attached: [Default_blossom_account_documentation_updated_to_take_into_account_pull_#184_changes.txt](https://github.com/blossom-project/blossom-initializr/files/3638568/Default_blossom_account_documentation_updated_to_take_into_account_pull_.184_changes.txt)

**Comment by RLejolivet** [comment]
Updating the doc with the proposed changes, thanks!
